### ISSUE TITLE
is_descendent function will fail if the ancestor ID isn't the immediate or first parent

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#255]
We need to ensure that if there are three or more levels that it is handled appropriately.

**Comment by dmseaton** [comment]
e.g.

- menu (1)
-- submenu (12)
--- subsubmenu (32)
---- menu item (43)

In the above example, using is_descendent(12) on the menu item will fail.

**Comment by juliotaylor** [comment]
@jrgmartin @dmseaton I am concerned this is a bug and has gone unfixed for 27 days. is it urgent?

**Comment by jrgmartin** [comment]
It’s not urgent, it’ll only affect sites where there is 4 levels of depth.

**Comment by jrgmartin** [comment]
I'm not going to fix this issue.  The way to fix is to get the children of the current post, loop over them, get their children, loop over them, etc.  This is hugely resource hungry.

As we rarely have this issue, I suggest that fix on a case by case basis rather than include it in Monolith core otherwise the majority of sites will suffer a performance hit for the benefit of the few.
